[book]
title = "O Livro Cargo"
author = "Alex Crichton, Steve Klabnik and Carol Nichols, with contributions from the Rust community"
description = "Cargo é o gerenciador de pacotes do Rust. O Cargo baixa as dependências do seu pacote Rust, compila seus pacotes, cria pacotes distribuíveis e os envia para o crates.io"
language = "pt-BR"

[output.html]
curly-quotes = true                                                                    # Enable smart-punctuation feature for more than quotes.
git-repository-url = "https://github.com/devtradutor/cargo_book_pt_br/tree/main/src"
edit-url-template = "https://github.com/devtradutor/cargo_book_pt_br/edit/main/{path}"
search.use-boolean-and = true
